-- Student App — local seed data, run by `npx supabase db reset` after the migrations.
--
-- Local development only: never run it against the hosted project. It creates two
-- Supabase Auth accounts with the demo password 123456 and links each one to a
-- student: senaiigorpereira / igor@email.com and 20231234 / marina@email.com.
--
-- Covers one full round trip: a subject with two topics, one question of each
-- of the six types, a quiz with all of them, and one submitted attempt whose
-- answers exercise every review status (correct, incorrect, pending_review)
-- plus unanswered questions. Marina has a longer streak, so the ranking has an
-- order to show.
--
-- Ids are generated by the database, so every insert below looks its parents
-- up by a natural key (e-mail, registration, name, question type). This relies
-- on there being exactly one question per type.

-- Supabase Auth reads the token columns as strings, so they must be '' instead of NULL.
INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, email_change, email_change_token_new, recovery_token
)
SELECT
  '00000000-0000-0000-0000-000000000000',
  gen_random_uuid(),
  'authenticated',
  'authenticated',
  account.email,
  extensions.crypt('123456', extensions.gen_salt('bf')),
  now(),
  '{"provider": "email", "providers": ["email"]}',
  '{}',
  now(),
  now(),
  '', '', '', ''
FROM (VALUES
  ('igor@email.com'),
  ('marina@email.com')
) AS account(email);

INSERT INTO auth.identities (
  id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at
)
SELECT
  gen_random_uuid(),
  u.id,
  u.id::text,
  jsonb_build_object('sub', u.id::text, 'email', u.email, 'email_verified', true),
  'email',
  now(),
  now(),
  now()
FROM auth.users u
WHERE u.email IN ('igor@email.com', 'marina@email.com');

INSERT INTO students (name, email, registration_id, course, auth_user_id)
SELECT student.name, student.email, student.registration_id, student.course, u.id
FROM (VALUES
  ('Igor Pereira', 'igor@email.com', 'senaiigorpereira', 'Análise e Desenvolvimento de Sistemas'),
  ('Marina Alves', 'marina@email.com', '20231234', 'Análise e Desenvolvimento de Sistemas')
) AS student(name, email, registration_id, course)
JOIN auth.users u ON u.email = student.email;

INSERT INTO subjects (name, short_label) VALUES ('Banco de Dados', 'BD');

INSERT INTO topics (subject_id, name)
SELECT s.id, t.name
FROM subjects s
CROSS JOIN (VALUES ('Modelagem ER'), ('Normalização')) AS t(name)
WHERE s.name = 'Banco de Dados';

INSERT INTO materials (topic_id, title, file_url)
SELECT id, 'Apostila — Modelagem ER', 'https://exemplo.local/materiais/modelagem-er.pdf'
FROM topics
WHERE name = 'Modelagem ER';

-- -----------------------------------------------------------------------------
-- Questions: one per type
-- -----------------------------------------------------------------------------

INSERT INTO questions (topic_id, type, prompt, explanation)
SELECT id, 'multiple_choice',
  'Qual construção representa um relacionamento muitos-para-muitos no modelo ER?',
  'Um relacionamento muitos-para-muitos vira uma entidade associativa com as chaves das duas entidades.'
FROM topics WHERE name = 'Modelagem ER';

INSERT INTO question_options (question_id, text, is_correct, order_index)
SELECT q.id, o.text, o.is_correct, o.order_index
FROM questions q
CROSS JOIN (VALUES
  ('Entidade associativa com as chaves das duas entidades', true, 1),
  ('Atributo multivalorado em uma das entidades', false, 2),
  ('Chave estrangeira única na entidade mais fraca', false, 3)
) AS o(text, is_correct, order_index)
WHERE q.type = 'multiple_choice';

INSERT INTO questions (topic_id, type, prompt, explanation)
SELECT id, 'multiple_answer',
  'Quais afirmações sobre normalização estão corretas?',
  'A 1FN exige valores atômicos e a 2FN elimina dependências parciais; normalizar reduz a redundância.'
FROM topics WHERE name = 'Normalização';

INSERT INTO question_options (question_id, text, is_correct, order_index)
SELECT q.id, o.text, o.is_correct, o.order_index
FROM questions q
CROSS JOIN (VALUES
  ('A 1FN exige valores atômicos', true, 1),
  ('A 2FN elimina dependências parciais', true, 2),
  ('A normalização aumenta a redundância dos dados', false, 3)
) AS o(text, is_correct, order_index)
WHERE q.type = 'multiple_answer';

INSERT INTO questions (topic_id, type, template, explanation)
SELECT id, 'single_choice',
  'Uma tabela na {{b1}} não possui dependências transitivas.',
  'A 3FN elimina dependências transitivas entre atributos não-chave.'
FROM topics WHERE name = 'Normalização';

INSERT INTO question_blanks (question_id, blank_key, order_index)
SELECT id, 'b1', 1 FROM questions WHERE type = 'single_choice';

INSERT INTO question_blank_options (blank_id, text, is_correct, order_index)
SELECT b.id, o.text, o.is_correct, o.order_index
FROM question_blanks b
JOIN questions q ON q.id = b.question_id AND q.type = 'single_choice'
CROSS JOIN (VALUES
  ('3FN', true, 1),
  ('1FN', false, 2)
) AS o(text, is_correct, order_index);

INSERT INTO questions (topic_id, type, template, explanation)
SELECT id, 'drag_and_drop',
  'A forma normal que exige valores atômicos é a {{s1}}.',
  'A 1FN é a forma normal que exige valores atômicos.'
FROM topics WHERE name = 'Normalização';

INSERT INTO question_terms (question_id, text, order_index)
SELECT q.id, t.text, t.order_index
FROM questions q
CROSS JOIN (VALUES ('1FN', 1), ('2FN', 2)) AS t(text, order_index)
WHERE q.type = 'drag_and_drop';

INSERT INTO question_slots (question_id, slot_key, correct_term_id, order_index)
SELECT q.id, 's1', t.id, 1
FROM questions q
JOIN question_terms t ON t.question_id = q.id AND t.text = '1FN'
WHERE q.type = 'drag_and_drop';

INSERT INTO questions (topic_id, type, prompt, max_length, reference_answer)
SELECT id, 'essay',
  'Explique, em uma frase, para que serve uma chave primária.',
  300,
  'A chave primária identifica de forma única cada linha de uma tabela.'
FROM topics WHERE name = 'Modelagem ER';

INSERT INTO questions (topic_id, type, prompt, template)
SELECT id, 'essay_blanks',
  'Complete a definição.',
  'Uma chave estrangeira referencia a {{b1}} de outra tabela.'
FROM topics WHERE name = 'Modelagem ER';

INSERT INTO question_blanks (question_id, blank_key, reference_answer, order_index)
SELECT id, 'b1', 'chave primária', 1 FROM questions WHERE type = 'essay_blanks';

-- -----------------------------------------------------------------------------
-- Quiz and upcoming exam
-- -----------------------------------------------------------------------------

INSERT INTO quizzes (title, subject_scope, subject_id, duration_minutes, difficulty)
SELECT 'Banco de Dados — Simulado 1', 'single', id, 10, 'hard'
FROM subjects WHERE name = 'Banco de Dados';

INSERT INTO quiz_questions (quiz_id, question_id, order_index)
SELECT z.id, q.id, ROW_NUMBER() OVER (ORDER BY q.id)
FROM quizzes z
CROSS JOIN questions q
WHERE z.title = 'Banco de Dados — Simulado 1';

INSERT INTO scheduled_exams (subject_id, exam_date, note)
SELECT id, CURRENT_DATE + 7, 'Simulado integrado disponível'
FROM subjects WHERE name = 'Banco de Dados';

-- -----------------------------------------------------------------------------
-- One submitted attempt: 1 correct, 1 incorrect, 1 pending review, 3 unanswered
-- -----------------------------------------------------------------------------

INSERT INTO quiz_attempts (quiz_id, student_id)
SELECT z.id, s.id
FROM quizzes z
CROSS JOIN students s
WHERE z.title = 'Banco de Dados — Simulado 1' AND s.registration_id = 'senaiigorpereira';

INSERT INTO quiz_attempt_answers (attempt_id, question_id, selected_option_id, review_status)
SELECT a.id, q.id, o.id, 'correct'
FROM quiz_attempts a
JOIN students s ON s.id = a.student_id AND s.registration_id = 'senaiigorpereira'
JOIN questions q ON q.type = 'multiple_choice'
JOIN question_options o ON o.question_id = q.id AND o.is_correct;

-- Only one of the two correct options was selected.
INSERT INTO quiz_attempt_answers (attempt_id, question_id, selected_option_ids, review_status)
SELECT
  a.id,
  q.id,
  (SELECT jsonb_agg(o.id) FROM question_options o WHERE o.question_id = q.id AND o.order_index = 1),
  'incorrect'
FROM quiz_attempts a
JOIN students s ON s.id = a.student_id AND s.registration_id = 'senaiigorpereira'
JOIN questions q ON q.type = 'multiple_answer';

INSERT INTO quiz_attempt_answers (attempt_id, question_id, essay_text, review_status)
SELECT a.id, q.id, 'Serve para identificar cada linha da tabela.', 'pending_review'
FROM quiz_attempts a
JOIN students s ON s.id = a.student_id AND s.registration_id = 'senaiigorpereira'
JOIN questions q ON q.type = 'essay';

-- -----------------------------------------------------------------------------
-- Study days: streak of 3 for Igor, 5 for Marina
-- -----------------------------------------------------------------------------

INSERT INTO student_activity_days (student_id, activity_date)
SELECT s.id, CURRENT_DATE - d
FROM students s
CROSS JOIN generate_series(0, 2) AS d
WHERE s.registration_id = 'senaiigorpereira';

INSERT INTO student_activity_days (student_id, activity_date)
SELECT s.id, CURRENT_DATE - d
FROM students s
CROSS JOIN generate_series(0, 4) AS d
WHERE s.registration_id = '20231234';

