-- Student App — students (docs/04-contratos-de-api.md §3.1, §3.2, §1.3).

-- Holds no personal data (LGPD): the Auth account's login is an access code
-- generated by the institution, and the student's name is typed in the app and
-- kept only in the browser.
create table students (
  id                 integer generated always as identity primary key,
  course             text not null default '',
  weekly_goal_target integer not null default 50 check (weekly_goal_target > 0),
  -- Accounts are created by the institution in Supabase Auth, with public signups
  -- disabled ([auth] enable_signup = false in supabase/config.toml).
  auth_user_id       uuid not null unique references auth.users (id) on delete cascade
);

comment on table students is 'Pre-provisioned student accounts; there is no public signup and no personal data.';
comment on column students.weekly_goal_target is 'Weekly goal in answered questions (RankingData.profile.weeklyGoalTarget).';
